layout_spectrum: 0.07806235
typography_spectrum: 0.6815004
color:
  saturation: 0.4536288
  lightness: 0.4652734
  brandStrength: 0.2959528
  brandColors:
    - '#FFFFFF'
    - '#30312F'
    - '#B3AC98'
    - '#656F38'
    - '#E1A30D'
  rhythmicContrast: 0.07773639
name: Lanipao Central School Library
